name: CI (android)

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/build-android.yml'
      - '**/CMakeLists.txt'
      - '**/.cmake'
      - '**/*.h'
      - '**/*.hpp'
      - '**/*.c'
      - '**/*.cpp'

  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '.github/workflows/build-android.yml'
      - 'examples/llama.android/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref && github.ref || github.run_id }}
  cancel-in-progress: true

env:
  GGML_NLOOP: 3
  GGML_N_THREADS: 1
  LLAMA_ARG_LOG_COLORS: 1
  LLAMA_ARG_LOG_PREFIX: 1
  LLAMA_ARG_LOG_TIMESTAMPS: 1

jobs:
  arm64:
    runs-on: ubuntu-latest

    env:
      NDK_VERSION: "29.0.14206865"

    steps:
      - name: Clone
        id: checkout
        uses: actions/checkout@v6
        
      - name: Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential ninja-build vulkan-tools libvulkan-dev vulkan-validationlayers spirv-tools spirv-headers glslang-dev glslang-tools glslc


      # note : disabled to spare some cache space (https://github.com/ggml-org/llama.cpp/pull/23789)
      #        for some reason, the ccache does not improve the build time in this case
      # example:
      #   cache off: https://github.com/ggerganov/tmp2/actions/runs/26534713799/job/78160400831
      #   cache on:  https://github.com/ggerganov/tmp2/actions/runs/26534713799/job/78224189394
      #
      #- name: ccache
      #  uses: ggml-org/ccache-action@v1.2.21
      #  with:
      #    key: android-ubuntu-arm64
      #    evict-old-files: 1d
      #    save: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: temurin

      - name: Setup Android SDK
        uses: android-actions/setup-android@40fd30fb8d7440372e1316f5d1809ec01dcd3699 # v4.0.1
        with:
          log-accepted-android-sdk-licenses: false

      - name: Install NDK
        run: |
          sdkmanager "ndk;${{ env.NDK_VERSION }}"
          echo "ANDROID_NDK=${ANDROID_SDK_ROOT}/ndk/${{ env.NDK_VERSION }}" >> $GITHUB_ENV

      - name: Build
        id: cmake_build
        run: |
          cmake -B build -G Ninja \
            -DCMAKE_FIND_ROOT_PATH_MODE_PACKAGE=BOTH \
            -DVulkan_INCLUDE_DIR=/usr/include/vulkan \
            -DCMAKE_TOOLCHAIN_FILE=${ANDROID_NDK}/build/cmake/android.toolchain.cmake \
            -DANDROID_ABI=arm64-v8a \
            -DANDROID_PLATFORM=android-28 \
            -DLLAMA_FATAL_WARNINGS=ON \
            -DGGML_BACKEND_DL=OFF \
            ​-DBUILD_SHARED_LIBS=OFF \
            -DLLAMA_LTO=ON \
            -DLLAMA_BUILD_TESTS=OFF \
            -DLLAMA_BUILD_EXAMPLES=ON \
            -DCMAKE_C_FLAGS="-O3 -gsplit-dwarf -g0 -gline-tables-only" \
            -DCMAKE_CXX_FLAGS="-O3 -gsplit-dwarf -g0 -gline-tables-only" \
            -DGGML_NATIVE=OFF \
            -DGGML_CPU_ARM_ARCH=armv9.2-a+dotprod+fp16+sve+i8mm+sve2 \
            -DGGML_CPU_KLEIDIAI=ON \
            -DGGML_NEON=ON \
            -DGGML_ARM_FMA=ON \
            -DGGML_OPENMP=OFF \
            -DGGML_OPENCL=OFF \
            -DGGML_VULKAN=ON \
            -DLLAMA_BUILD_BORINGSSL=ON \
            -DGGML_RPC=ON 
          time cmake --build build --config Release -j $(nproc)
          
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: llama-android-vulkan
          path: build/bin/
          if-no-files-found: error
